"""Markdown exporter — drop straight into a pentest report."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from ..scanner import ScanResult

_SEV_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}


def _host_section(result: ScanResult) -> str:
    lines: list[str] = []
    grade = result.grade.letter if result.grade else "?"
    lines.append(f"## {result.host}:{result.port}  —  Grade `{grade}`\n")

    if not result.reachable:
        lines.append(f"> Unreachable: {result.error}\n")
        return "\n".join(lines)

    if result.ip:
        lines.append(f"- **IP:** {result.ip}")
    if result.grade:
        lines.append(f"- **Score:** {result.grade.score}/100")
        for cap in result.grade.caps:
            lines.append(f"  - _cap:_ {cap}")
    lines.append("")

    # Protocols
    lines.append("### Protocols\n")
    lines.append("| Protocol | Supported |")
    lines.append("|---|---|")
    for proto, ok in result.protocols.items():
        lines.append(f"| {proto} | {'✅' if ok else '❌'} |")
    lines.append("")

    # Ciphers
    lines.append("### Cipher suites\n")
    for proto, ciphers in result.ciphers.items():
        if not ciphers:
            continue
        lines.append(f"**{proto}**\n")
        lines.append("| Cipher | Bits | PFS | AEAD | Strength |")
        lines.append("|---|---|---|---|---|")
        for c in ciphers:
            lines.append(
                f"| `{c.name}` | {c.bits} | {'✓' if c.forward_secret else '—'} "
                f"| {'✓' if c.aead else '—'} | {c.strength} |"
            )
        lines.append("")

    # Certificate
    cert = result.certificate
    if cert and not cert.errors:
        lines.append("### Certificate\n")
        lines.append(f"- **Subject:** {cert.subject}")
        lines.append(f"- **Issuer:** {cert.issuer}")
        if cert.san:
            lines.append(f"- **SAN:** {', '.join(cert.san[:12])}")
        lines.append(
            f"- **Valid until:** {cert.not_after} " f"({cert.days_until_expiry} days)"
        )
        lines.append(f"- **Key:** {cert.public_key_type} {cert.public_key_bits}-bit")
        lines.append(f"- **Signature:** {cert.signature_algorithm}")
        flags = []
        if cert.self_signed:
            flags.append("self-signed")
        if cert.expired:
            flags.append("expired")
        if cert.hostname_mismatch:
            flags.append("hostname mismatch")
        if cert.uses_sha1:
            flags.append("SHA-1")
        lines.append(f"- **Issues:** {', '.join(flags) if flags else 'none'}")
        lines.append("")

    # Vulnerabilities
    present = [v for v in result.vulnerabilities if v.present]
    if present:
        lines.append("### Vulnerabilities\n")
        lines.append("| Severity | Finding | Reference |")
        lines.append("|---|---|---|")
        for v in sorted(present, key=lambda x: x.severity):
            emoji = _SEV_EMOJI.get(v.severity, "")
            lines.append(f"| {emoji} {v.severity} | {v.name} | {v.reference} |")
        lines.append("")

    # Recommendations
    if result.recommendations:
        lines.append("### Recommendations\n")
        for r in result.recommendations:
            emoji = _SEV_EMOJI.get(r.severity, "")
            ref = f" _(ref: {r.reference})_" if r.reference else ""
            lines.append(f"- {emoji} **{r.title}** — {r.detail}{ref}")
        lines.append("")

    return "\n".join(lines)


def export(results: list[ScanResult], tool_version: str = "") -> str:
    header = [
        "# WhatTheCipher — TLS/SSL Assessment Report\n",
        f"_Generated by WhatTheCipher v{tool_version}_\n" if tool_version else "",
        f"**Hosts scanned:** {len(results)}\n",
    ]
    # Executive summary table
    header.append("## Executive summary\n")
    header.append("| Host | Grade | Protocols | Critical | High |")
    header.append("|---|---|---|---|---|")
    for r in results:
        grade = r.grade.letter if r.grade else "?"
        protos = " ".join(p for p, ok in r.protocols.items() if ok) or "—"
        crit = sum(1 for v in r.vulnerabilities if v.present and v.severity == "critical")
        high = sum(1 for v in r.vulnerabilities if v.present and v.severity == "high")
        header.append(f"| {r.host}:{r.port} | {grade} | {protos} | {crit} | {high} |")
    header.append("")

    body = "\n".join(_host_section(r) for r in results)
    return "\n".join(header) + "\n" + body


def write(results: list[ScanResult], path: str, tool_version: str = "") -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(export(results, tool_version))
